#' ONI replicate
#'
#' Create one replicate of ONI time series using equation (4) in Burgers (1999) and parameter values reported in the same paper.
#' @inheritParams ONI_rep
#' @return A vector of the ONI time series.
#' @export
one_ONI_rep <- function(num.years) {

    a  <- 0.94
    b  <- 0.13
    k  <- 0.86
    ve <- 0.24 # variance of epsilon

    num.months <- num.years * 12
    epsilon  <- rnorm(num.months, 0, sqrt(ve)) # white noise
    x    <- rep(0, num.months)
    x[1] <- rnorm(1, 0, sqrt(ve))   # x0 = 0, x1 = epsilon0
    x[2] <- 2*a*x[1] + epsilon[1] - k*x[1]

    for (i in 2:(num.months - 1)){
        x[i+1] <- 2*a*x[i] - (a^2 + b^2)*x[i-1] + epsilon[i] - k*epsilon[i-1]
    }

    x
}

#' ONI replicates
#'
#' Generate multiple stochastic replicates of ONI time series according to Burgers (1999).
#' @param ONI.obs A data frame of observed ONI with three columns (year, month, ONI). By default, the replicates will have the same years as ONI.obs, unless `years` is provided.
#' @param years If provided, the replicates will have these years.
#' @param num.reps Number of replicates to be generated. Default is 100.
#' @param var.cor Whether variance correction is performed. Setting `var.cor = TRUE` will ignore `trim`.
#' @param trim Used to cut off values that are too high or too low. Values that are more than `trim * max(abs(obs))` will be set to `max(abs(obs))`. Default is 2. Supply `trim = NULL` if you don't want trimming.
#' @return A data.table of 4 columns (rep, year, month, ONI).
#' @export
ONI_reps <- function(ONI.obs, years = NULL, num.reps = 100, trim = 2, var.cor = FALSE) {

    if (is.null(years)) years <- unique(ONI.obs$year)
    num.years <- length(years)
    # This returns a matrix, one row for each time step, one column for each replicate
    reps <- replicate(num.reps, one_ONI_rep(num.years))
    # Trim or variance correction if necessary
    if (var.cor) {
        hist.sd <- sd(ONI.obs$ONI)
        rep.sd <- sd(c(reps))
        reps <- reps / rep.sd * hist.sd
    } else if (!is.null(trim)) {
        norm.val <- trim * max(abs(ONI.obs$ONI))
        reps[which(reps >  norm.val)] <-  norm.val
        reps[which(reps < -norm.val)] <- -norm.val
    }

    data.table(rep = rep(1:num.reps, each = 12*num.years),
               year = rep(years, each = 12),
               month = rep(1:12, times = num.reps),
               ONI = c(reps))
}

#' Streamflow replicates with ARMAX
#'
#' Generate stochastic replicates of streamflow with the ARMAX model. If exogneous inputs are not provided then the ARMA model will be used.
#' @param ONI.obs A data frame of observed streamflow with three columns (year, month, Q). By default, the replicates will have the same years as Q.obs, unless `years` is provided.
#' @inheritParams ONI_reps
#' @param model A time series model, e.g., that generated by `forecast::Arima()`.
#' @param X Exogeneous input, a data.table with 4 columns (rep, year, month, X). If there are more than 4 columns, the desirable column name to be used as exogenous input should be given in `X.name`; otherwise the function will take the 4th column by default. If provided, `num.reps` will be ignored.
#' @export
Q_ARMAX <- function(Q.obs, model, X = NULL, X.name = NULL,
                    years = NULL, num.reps = 100, trim = 2, trans = 'log') {

    if (is.null(X)) { # ARMA
        if (is.null(years)) years <- Q.obs[, year]
        num.years <- length(years)
        ans <- rbindlist(
            lapply(1:num.reps, function(k)
                data.table(rep = k,
                           year = years,
                           month = rep(1:12, num.years),
                           Q = as.vector(simulate(model, n = num.years))
                           )
                )
            )
    }
    else { # ARMAX
        if (is.null(X.name)) X.name <- colnames(X)[4]
        X <- copy(X)
        setnames(X, old = X.name, new = 'X')
        ans <- copy(X)[, Q := as.vector(simulate(model, xreg = X)), by = rep]
    }
    if (trans == 'log') ans[, Q := exp(Q)]
    if (!is.null(trim)) ans[Q > trim * max(Q.obs$Q), Q := trim * max(Q.obs$Q)]
    ans[]
}


## @param Q.other Other flow processes not modelled by `model`, for example, diversion from another catchment. This will be added to the replicates. Must have the same structure as `Q.obs`.


# write.reps <- function(all_reps, path, norm_val) {
#
#     # Write only ENSO reps for classification
#     lapply(unique(all_reps$reps),
#            function(x) {
#                case <- filter(all_reps, reps == x) %>%
#                    select(year, month, anom)
#                write.csv(case, file = paste0(path, 'ENSO_', x, '.csv'), row.names = FALSE)
#            }
#     )
#     # Write the reps in Christoph's template
#     lapply(unique(all_reps$reps),  # For each reps
#            function(x) {
#                case   <- filter(all_reps, reps == x) # Select current rep
#                Q_lag1 <- lag(case$cms_wU)[-(1:12)]    # Shift Q back by 1 month, omit first year (1967)
#                case %>%
#                    filter(year >= 1968) %>%   # Remove 1967
#                    mutate(day = 1,
#                           hour = 0,
#                           min = 0,
#                           Q = cms_wU,
#                           seasonal = seasons,
#                           ENSO_4avg_normalized = (anom_rm + norm_val) / (2*norm_val),
#                           Inflow_norm = Q_lag1 / Q.norm.val) %>%
#                    select(year, month, day, hour, min, Q, seasonal, ENSO_4avg_normalized, Inflow_norm) %>%
#                    round(2) %>%
#                    write.csv(file = paste0(path, x,'.csv'), row.names = FALSE)
#            }
#     )
# }
#
# reps.withVC <- replicator(n.reps, n.years, var.cor = TRUE)
# norm.val.VC <- max(c(max(abs(reps.withVC$anom)), max(abs(nino.C$anom))))
# #write.reps(reps.withVC, path = 'Output/New_reps_VC/', norm_val = norm.val.VC)
#
# ggplot() +
#     geom_line(data = reps.withVC, aes(year + month/12, anom, group = reps), colour = 'grey') +
#     geom_line(data = nino.C, aes(year + month/12, anom), colour = 'black')
#
# ggplot() +
#     geom_line(data = reps.withVC, aes(year + month/12, cms, group = reps), colour = 'grey') +
#     geom_line(data = Q, aes(year + month/12, cms), colour = 'black')
#
